on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

permissions:
  contents: write

jobs:
  pkgdown:
    uses: ggsegverse/.github/.github/workflows/pkgdown.yaml@main
