on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: '17 3 * * 0'

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    uses: ggsegverse/.github/.github/workflows/R-CMD-check.yaml@main
    with:
      extra-repositories: https://ggsegverse.r-universe.dev
      build-args: 'c("--no-manual", "--compact-vignettes=gs+qpdf")'
